### ISSUE TITLE
Is this still being mantained?

### ISSUE THREAD

**Issue by ThePirate42** [electrickite/mkinitcpio-tpm2-encrypt#8] opened 2022-01-06 13:06 UTC
I ask because apparently there hasn't been an update in a while. I guess this software doesn't really need an update, but if a bug was discovered you would still patch it right?

**Comment by electrickite** [comment] 2022-01-06 15:31
The project is still being maintained. The hook currently does what it needs to do, so updates will likely be infrequent. If bugs are discovered, and patches submitted I will be happy to review. Due to the nature of TPM devices and individual system configurations, bugs can be fairly difficult to reproduce, I'm afraid.

Incidentally, there have been a number of TPM users I'm aware of moving to a systemd-cryptenroll based configuration. If you're using systemd, it might be worth looking in to as an alternative.

**Comment by ThePirate42** [comment] 2022-01-08 01:45
Nah I don't think I will do that unless I really need to (does the systemd version have some particular advantage?), my mkinitcipio.conf and my kernel parameters are already all configured with busybox hooks. BTW thank you for your work!

**Closed as completed** 2022-08-01 02:22 UTC
